### ISSUE TITLE
Repositories

### ISSUE THREAD

**Issue by lance0821** [mapzen/opzworks#12]
I would like to deploy Mapzen and Pelias to integrate with an existing application I have. Are there public repositories hosting the cookbooks that I can add to the Berksfile?

**Comment by heffergm** [comment]
Hi. Unfortunately there are not, mainly because Pelias consists mostly of process, i.e. loading of data, the automation for which is presently tightly coupled to our environment.  

That said, you can use the public elastic search cookbooks to get that dependency installed, and installing the Pelias API only requires nodejs and a copy of the code.  Again, all easily done with existing public cookbooks. If you have more questions get in touch at help@mapzen.com.

**Comment by heffergm** [comment]
@lance0821 apologies, that email address should be hello@mapzen.com!

**Comment by lance0821** [comment]
I actually did on January 18th... But haven't heard anything back

**Comment by heffergm** [comment]
@kathleenLD did you see any email come across Zendesk from @lance0821 ?
